# -*- coding: utf-8 -*-
"""題庫（自動修復後重生成）"""

QC = [
{
 "n": "A4-1", "ty": "concept",
 "q": "只收 /rosout topic 當作日誌來源的盲區是？",
 "o": ["rclcpp 節點的 log 不會進 /rosout",
       "無法按 severity 過濾訊息",
       "訊息缺少時間戳欄位",
       "rcl 初始化前的錯誤與非 ROS 行程的輸出都收不到"],
 "a": 3,
 "ex": "/rosout 只有初始化完成的 ROS 節點會發——最關鍵的啟動失敗訊息恰恰在它涵蓋之外。A 說反了，rclcpp 預設會發。B、C 的欄位都存在。",
 "dig": {"s": "日誌收集路徑的覆蓋範圍", "m": "訂 /rosout 就等於收到了系統所有 log", "t": "崩在 rclcpp init 之前的訊息只在 stdout/stderr——所以要用 journald 收行程輸出，/rosout 只是輔助", "p": "設計雙路徑日誌架構：stdout→journald 為主、/rosout 為輔，說明各補什麼盲區"}},
{
 "n": "A4-1", "ty": "debug",
 "q": "想在不重啟節點的情況下暫時看到某節點的 DEBUG log，做法是？",
 "o": ["編輯 unit 檔的 Environment 後 daemon-reload",
       "呼叫該節點的 set_logger_level service 動態調整",
       "送 SIGHUP 讓節點重讀日誌設定",
       "在 journald 過濾器把等級門檻調低"],
 "a": 1,
 "ex": "logger level 是執行期狀態，有標準 service 可調。A 環境變數要重啟行程才生效。C ROS 2 節點沒有 SIGHUP 重載日誌的慣例。D journald 只能過濾已產生的訊息——DEBUG 沒被產生就過濾不出來。",
 "dig": {"s": "執行期動態調整 log level", "m": "log level 是啟動參數，要改就得重啟", "t": "產生端的等級是活的節點狀態，可用 service 即時調——值班時的關鍵技能", "p": "給我用 ros2 service call 調某節點 logger level 的確切指令與驗證方式"}},
{
 "n": "A4-1", "ty": "scenario",
 "q": "設計機器人日誌欄位規範時，「事件碼」（如 CAM_TIMEOUT_001）的價值主要在？",
 "o": ["讓可觀測管線能按事件聚合統計與精準告警",
       "縮短訊息長度節省儲存空間",
       "滿足 ROS 2 logging API 的格式要求",
       "讓 log 檔案可以被壓縮得更小"],
 "a": 0,
 "ex": "結構化事件碼讓「這型故障出現幾次」從 grep 猜字串變成可靠查詢——你的資料工程直覺。B、D 空間影響微乎其微。C API 沒有這種要求。",
 "dig": {"s": "結構化日誌的查詢價值", "m": "log 是給人讀的，寫清楚的中文/英文描述就好", "t": "log 同時是資料：自由文字無法聚合，事件碼+欄位才能進 metrics 與告警管線", "p": "幫我設計機器人平台的事件碼命名規範（子系統×類型×編號），給 10 個範例"}},
{
 "n": "A4-2", "ty": "concept",
 "q": "rosbag2 的 snapshot mode 解決的核心問題是？",
 "o": ["長時間錄製時的磁碟空間壓縮",
       "多 topic 之間的時間戳對齊",
       "事故總在「沒在錄的時候」發生",
       "錄製對系統效能的影響降到零"],
 "a": 2,
 "ex": "平時只寫記憶體環形緩衝，事件觸發才把最後 N 秒落盤——行車記錄器邏輯。A 壓縮是另一個功能。B 對齊本來就靠訊息時間戳。D 緩衝仍有成本，只是不寫磁碟。",
 "dig": {"s": "snapshot 錄製的事故取證模式", "m": "要取證就 24 小時全錄，硬碟夠大就好", "t": "全錄在影像等級的流量下一天數百 GB 不現實；snapshot 以觸發器換空間，抓住事故前的黃金 30 秒", "p": "給我 rosbag2 snapshot mode 的設定檔與觸發 service 的呼叫方式，含緩衝大小的估算方法"}},
{
 "n": "A4-2", "ty": "debug",
 "q": "錄 bag 時某個 BEST_EFFORT 的影像 topic 完全沒錄到資料，其他 topic 正常。最可能的原因是？",
 "o": ["MCAP 格式不支援影像這類大訊息",
       "錄製端訂閱 QoS 與發布端不相容（未套用 override）",
       "影像 topic 必須先經過壓縮編碼，rosbag 才能錄製",
       "bag 的單檔大小上限已被觸發"],
 "a": 1,
 "ex": "rosbag 也是訂閱者，QoS 相容規則照樣適用——對特殊 QoS 的 topic 要用 override 檔對齊。A MCAP 對大訊息毫無問題。C 沒有這種限制。D 上限觸發會分檔，不會單獨漏某 topic。",
 "dig": {"s": "rosbag 作為訂閱者的 QoS 行為", "m": "rosbag record 是特權工具，什麼 topic 都錄得到", "t": "它就是普通 subscriber，QoS 不合照樣安靜收不到——qos override yaml 是標準解", "p": "給我 rosbag2 的 QoS override 檔範例，讓它能穩定錄到 sensor data profile 的 topic"}},
{
 "n": "A4-2", "ty": "scenario",
 "q": "你想用資料工程技能離線分析上千個 MCAP 檔裡的 /diagnostics。最合適的路徑是？",
 "o": ["逐檔 ros2 bag play 重播回 ROS 系統再收集",
       "先全部轉成 CSV 再匯入資料庫",
       "寫 ROS 2 節點訂閱重播流做即時統計",
       "用 mcap Python 函式庫直接讀檔解碼進 pandas/DuckDB"],
 "a": 3,
 "ex": "MCAP 是自述格式，Python API 可離線直讀免起 ROS——這正是它對資料工程友善之處。A 與 C 都要付重播的即時等待成本，千檔不可行。B 多一層失真的中間格式且丟型別。",
 "dig": {"s": "bag 資料的離線批次處理", "m": "ROS 的資料只有 ROS 工具能處理", "t": "MCAP 內嵌 schema，任何語言的 reader 都能獨立解碼——bag 就是機器人的 parquet", "p": "給我一段 Python：掃描資料夾內所有 MCAP，抽出某 topic 為 DataFrame 並算每檔的頻率統計"}},
{
 "n": "A4-3", "ty": "concept",
 "q": "Jetson 機器人的 Prometheus 監控中，除了 CPU/記憶體，最值得加的一組硬體指標是？",
 "o": ["GPU 風扇的轉速曲線",
       "溫度與節流（throttling）狀態",
       "eMMC 儲存模組的循序讀寫速度基準",
       "USB 匯流排的列舉次數"],
 "a": 1,
 "ex": "Jetson 過熱會安靜降頻，症狀是「下午比早上慢」——沒有溫度指標根本無從關聯。A 風扇轉速是輔助，節流狀態才是直接證據。C、D 是偶發診斷項不是常駐指標。",
 "dig": {"s": "邊緣裝置的關鍵健康指標", "m": "監控 CPU 使用率就能看出效能問題", "t": "降頻時 CPU% 看起來正常甚至更高，但時脈掉了——要監控溫度、節流事件與實際時脈", "p": "tegrastats 的輸出怎麼轉成 Prometheus metrics？給我一個最小 exporter 的寫法"}},
{
 "n": "A4-3", "ty": "tradeoff",
 "q": "告警規則設「topic 頻率 < 25Hz 持續 30 秒才告警」而非「一跌破就告警」，理由是？",
 "o": ["Prometheus 的取樣間隔無法低於 30 秒",
       "低於 30 秒的中斷不可能影響功能",
       "頻率量測本身有雜訊，瞬時值不可信",
       "用持續時間換取訊噪比——瞬時抖動不該吵醒值班"],
 "a": 3,
 "ex": "告警的敵人是狼來了：for 子句過濾瞬時抖動，留下真正的持續異常。A 取樣間隔可以到秒級。B 短中斷可能有影響，但告警疲勞的代價更大——這是取捨不是無影響。C 雜訊存在但不是主因。",
 "dig": {"s": "告警規則的訊噪比設計", "m": "告警越靈敏越好，寧可誤報不可漏報", "t": "誤報會訓練人類忽略告警——最終漏掉真事故；for 持續時間是第一道訊噪比開關", "p": "幫我為機器人平台設計三級告警策略（page/ticket/dashboard-only），各配觸發條件範例"}},
{
 "n": "A4-3", "ty": "scenario",
 "q": "主管問「機器人隊這週的健康狀況如何」。哪個指標設計最能直接回答？",
 "o": ["每台機器人的可用時間比例與故障次數的趨勢圖",
       "所有節點的 CPU 使用率總覽",
       "DDS 封包的重傳率統計",
       "各 topic 的平均訊息大小分佈"],
 "a": 0,
 "ex": "可用性與故障率是業務層指標，直接對應「健康」的語意——對非技術受眾也可讀。B、C、D 都是工程診斷指標，回答不了「所以呢」。",
 "dig": {"s": "業務層指標 vs 工程診斷指標", "m": "把所有技術指標放上 dashboard，資訊越多越好", "t": "dashboard 要分層：高層看可用性/故障率，工程層才看 CPU/頻率——JD 的溝通職責就從指標分層開始", "p": "幫我定義機器人的『可用性』：怎麼算 uptime？降級狀態算不算 up？給出可實作的定義"}},
{
 "n": "A4-4", "ty": "concept",
 "q": "foxglove_bridge 讓瀏覽器看到 ROS 2 系統的機制是？",
 "o": ["把 RViz 畫面串流成 WebRTC 視訊",
       "在機器人上跑一個 WebSocket server 轉發訂閱的 topic 資料",
       "把 DDS 的原生流量直接鏡射到瀏覽器開啟的 UDP socket",
       "定期把 bag 片段上傳到雲端再由網頁下載"],
 "a": 1,
 "ex": "bridge 是機器人端的 WebSocket 服務，按需訂閱並以自訂協定轉發，瀏覽器端負責渲染。A 傳的是資料不是畫面。C 瀏覽器無法收原生 UDP/DDS。D 那是離線回放的路徑。",
 "dig": {"s": "foxglove_bridge 的架構", "m": "Foxglove 要裝在機器人上，就像 RViz 一樣是本機 GUI", "t": "渲染在你的瀏覽器、資料經 WebSocket 拉取——機器人端只要一個無 GUI 的 bridge 節點", "p": "frame rate 高的影像 topic 經 WebSocket 會吃多少頻寬？教我估算並設定 topic 白名單"}},
{
 "n": "A4-4", "ty": "scenario",
 "q": "值班 layout 的第一原則是？",
 "o": ["把所有 topic 都放上去避免遺漏",
       "以 3D 視圖為中心，因為最直觀",
       "首屏回答「現在健康嗎」",
       "只放 log 面板，其他資訊干擾判斷"],
 "a": 2,
 "ex": "值班視圖是決策工具：先分診（健康總覽、告警燈）再深查。A 資訊過載讓真異常淹沒。B 3D 視圖對多數平台故障沒有診斷力。D log 是深查層不是首屏。",
 "dig": {"s": "運維視圖的資訊層級設計", "m": "dashboard 就是把資料都顯示出來", "t": "視圖分層：分診（紅綠燈）→定位（哪個子系統）→深查（log/raw topic）——每層回答一個問題", "p": "幫我列出機器人值班首屏該有的 6 個元件與各自回答的問題"}},
{
 "n": "A4-4", "ty": "debug",
 "q": "Foxglove 連上遠端機器人後，影像 topic 播起來延遲三秒且越來越久。合理的第一步是？",
 "o": ["把影像切到 compressed 版本或降低訂閱頻率",
       "重啟 foxglove_bridge 清空狀態",
       "改用有線網路取代 Wi-Fi",
       "把瀏覽器換成桌面版 Foxglove"],
 "a": 0,
 "ex": "越來越久=排隊堆積=頻寬不足，先降流量驗證假設。B 重啟只清空佇列，馬上再堆。C 可能有效但成本高且未驗證假設。D 桌面版走同一條 WebSocket，無濟於事。",
 "dig": {"s": "串流延遲堆積的診斷", "m": "延遲高就是工具或網路爛，換一個就好", "t": "遞增延遲是生產快於消費的排隊指紋——先把流量降到頻寬以下，延遲曲線立刻說話", "p": "教我算一條 640x480@30fps 未壓縮影像 topic 的頻寬需求，與 JPEG 壓縮後的對比"}},
{
 "n": "A4-5", "ty": "concept",
 "q": "launch_testing 相對單元測試的獨特價值是？",
 "o": ["執行速度更快，適合放 pre-commit",
       "不需要 ROS 環境就能執行",
       "真的把節點跑起來",
       "能直接量測程式碼覆蓋率"],
 "a": 2,
 "ex": "它起真行程、發真訊息，抓的是單元測試看不到的整合斷裂（remap 錯、參數缺、QoS 不合）。A 恰恰較慢。B 恰恰需要完整環境。D 覆蓋率是單元測試的強項。",
 "dig": {"s": "ROS 2 的測試層級", "m": "單元測試都綠了系統就沒問題", "t": "ROS 系統的 bug 大多在接縫（名稱、QoS、時序）——要有起真節點的整合層才抓得到", "p": "給我一個 launch_testing 範例：起一個節點、驗證它 5 秒內發布了預期 topic"}},
{
 "n": "A4-5", "ty": "debug",
 "q": "CI 在 x86 runner 上 build 出的 image，Jetson pull 下來起不動（exec format error）。原因與正解是？",
 "o": ["JetPack 版本太舊，升級後即可執行",
       "image 是 amd64 架構",
       "Jetson 的 Docker 不支援 GitHub registry",
       "image 缺少 CUDA runtime 層"],
 "a": 1,
 "ex": "exec format error 是架構不符的鐵證——CI 要交叉建 arm64。A JetPack 版本不會造成這個錯誤。C registry 來源無關架構。D 缺 CUDA 的症狀是執行期找不到函式庫，不是 exec format。",
 "dig": {"s": "多架構 image 的建置與識別", "m": "Docker image 是通用的，哪裡 build 哪裡跑", "t": "image 綁 CPU 架構；buildx+QEMU 或原生 arm64 runner 才能產 Jetson 可用的 image", "p": "給我 GitHub Actions 用 buildx 建 multi-arch（amd64+arm64）並推 registry 的 workflow 範例"}},
{
 "n": "A4-5", "ty": "tradeoff",
 "q": "industrial_ci 相對於自己手刻 colcon 流程的主要優勢是？",
 "o": ["把 rosdep、build、test 的順序與環境封裝成標準流程",
       "執行速度比手刻流程快數倍",
       "可以免費使用 GitHub 提供的 GPU runner 加速編譯",
       "能自動修復失敗的測試案例"],
 "a": 0,
 "ex": "它把 ROS 生態的 CI 慣例（含各發行版矩陣）做成配置即用，少踩自建流程的環境坑。B 速度相近，優勢不在快。C 與 GPU runner 無關。D 沒有自動修測試這種魔法。",
 "dig": {"s": "標準化 CI 工具 vs 自建流程", "m": "CI 不過就是跑幾行指令，自己寫 yaml 就好", "t": "rosdep 解析、underlay 準備、測試結果彙整都有細節；標準工具把社群踩過的坑變成預設值", "p": "展示同一個 package 用 industrial_ci 與手刻 colcon workflow 的 yaml 對比，標出手刻版容易漏的步驟"}},
{
 "n": "A4-6", "ty": "scenario",
 "q": "機器人現場只有 4G 網路。資料上傳策略的正確分級是？",
 "o": ["全部資料即時上傳，掉線就丟棄",
       "全部先存本地，每晚一次全量上傳",
       "metrics 即時、snapshot 事件觸發、全量 bag 排程或不傳",
       "只即時上傳 log，bag 與 metrics 全部留存在機器人本地"],
 "a": 2,
 "ex": "按價值密度分級：告警要即時、事故取證要盡快、原始資料可等或抽樣。A 頻寬撐不住還丟掉最貴的事故資料。B 讓告警延遲一整天。D metrics 不傳等於雲端全盲。",
 "dig": {"s": "受限頻寬下的資料分級策略", "m": "資料都很重要，能傳就全傳", "t": "頻寬是預算：每類資料標上價值密度與時效需求，得到的排序就是上傳策略", "p": "幫我算：10 台機器人、每台 4G 月流量 20GB，metrics/log/snapshot 各分多少預算？給推導過程"}},
{
 "n": "A4-6", "ty": "debug",
 "q": "斷線續傳測試中，恢復網路後同一個 bag 在雲端出現了兩份。root cause 方向是？",
 "o": ["上傳缺乏冪等性設計（無固定 key 判重）",
       "4G 行動網路在基地台切換時的封包重複送達",
       "雲端儲存的最終一致性延遲",
       "MCAP 檔案格式不支援續傳"],
 "a": 0,
 "ex": "重試邏輯沒有冪等 key，斷點後整檔重傳造成重複——分散式系統的經典課題。B TCP 層已處理封包重複。C 最終一致性造成的是暫時讀不到，不是永久兩份。D 續傳是上傳協定的事與格式無關。",
 "dig": {"s": "上傳管線的冪等性設計", "m": "重試上傳最多浪費流量，不會有正確性問題", "t": "at-least-once 重試必然產生重複，要嘛以確定性 key 覆寫、要嘛下游去重——二選一必須做", "p": "用 S3 的條件寫入或固定 object key 設計一個冪等上傳協定，給我具體流程"}},
{
 "n": "A4-6", "ty": "concept",
 "q": "雲端側「按機器人×時間窗×告警類型查到對應 bag」的索引，最小可行的實作是？",
 "o": ["把所有 bag 的原始內容逐筆解碼灌進大型的資料倉儲",
       "上傳時寫一筆含機器人、時間窗、事件的 metadata 供查詢",
       "靠物件命名規則，用檔名 glob 搜尋",
       "為每個 bag 建立全文檢索索引"],
 "a": 1,
 "ex": "metadata 表（哪怕是 DynamoDB/SQLite/JSON lines）就滿足查詢需求，成本極低。A 是重型方案，之後再演進。C 檔名塞不下多維條件且無法範圍查詢。D 全文檢索對二進位 bag 無意義。",
 "dig": {"s": "資料湖的最小索引設計", "m": "檔案丟上 S3 命名規則清楚一點就查得到了", "t": "物件儲存不是資料庫：範圍與多維查詢要靠 metadata 層——這是 data catalog 的最小版本", "p": "幫我設計這張 metadata 表的 schema 與寫入時機，考慮上傳失敗時的一致性"}},
{
 "n": "A5-1", "ty": "debug",
 "q": "Jetson Orin Nano 拿到手直接刷最新 JetPack 6 的 SD 卡映像，結果開不了機。最常見的原因是？",
 "o": ["SD 卡容量超過 Jetson 支援上限",
       "JetPack 6 只支援 NVMe 不支援 SD 卡開機",
       "板上 UEFI 韌體版本過舊",
       "映像檔要用 NVIDIA 專用工具而非 dd/Etcher 燒錄"],
 "a": 2,
 "ex": "Orin Nano 的韌體升級路徑是著名地雷：舊出廠韌體不認新 JetPack 的開機鏈，要先走韌體升級。A 容量沒有這種上限。B SD 卡開機仍支援。D Etcher 燒錄完全可行。",
 "dig": {"s": "Jetson 韌體與 JetPack 版本的相依關係", "m": "刷機就像燒 Raspberry Pi 映像，插卡就能開機", "t": "Jetson 的 UEFI 韌體存在板上 QSPI，與 SD 卡映像版本必須匹配——升級順序錯了就開不了機", "p": "給我 Orin Nano 從未知韌體版本安全升到 JetPack 6.x 的完整決策流程圖"}},
{
 "n": "A5-1", "ty": "concept",
 "q": "nvpmodel 的電源模式（如 15W/25W）實際上在控制？",
 "o": ["電池的充放電曲線",
       "可用的 CPU/GPU 核心數與最大時脈的組合",
       "作業系統的行程排程優先級",
       "USB 與 GPIO 週邊的供電開關"],
 "a": 1,
 "ex": "電源模式是核心數×時脈上限的預設組合表，功耗是結果。A Jetson 開發板不管電池。C 排程仍是 kernel 的事。D 週邊供電不在模式表裡。",
 "dig": {"s": "Jetson 電源模式的機制", "m": "省電模式只是降低亮度或睡眠策略之類的系統設定", "t": "nvpmodel 直接關核心、壓時脈——效能測試前不確認模式，數字就沒有意義", "p": "教我用 nvpmodel 與 jetson_clocks 的組合做一次可重現的效能基準測試流程"}},
{
 "n": "A5-1", "ty": "tradeoff",
 "q": "rootfs 放 NVMe SSD 而非 SD 卡，最重要的理由是？",
 "o": ["隨機 IO 效能與寫入耐久度",
       "SD 卡插槽會佔用 PCIe 通道",
       "NVMe 才支援檔案系統加密",
       "SD 卡無法容納 JetPack 的完整安裝"],
 "a": 0,
 "ex": "log、bag、apt 都是持續寫入，SD 卡的隨機寫與壽命是瓶頸；24/7 系統上這是可靠性投資。B 兩者通道獨立。C 加密與媒介無關。D 大容量 SD 卡裝得下。",
 "dig": {"s": "儲存媒介對長期運行可靠性的影響", "m": "SD 卡便宜好用，跑得動就沒必要換", "t": "問題不在跑不跑得動而在寫入放大與磨損——長期錄 bag 的系統，SD 卡故障是時間問題", "p": "幫我估算：每天寫 20GB log+bag 的機器人，一張 128GB TLC SD 卡大概多久寫穿？"}},
{
 "n": "A5-2", "ty": "concept",
 "q": "JetPack 6（Ubuntu 22.04）想跑 ROS 2 Jazzy（目標 24.04），標準解法是？",
 "o": ["把 Jetson 的系統升級到 Ubuntu 24.04",
       "從原始碼在 22.04 上編譯 Jazzy",
       "用容器跑 Jazzy",
       "改用 ROS 2 Humble 放棄 Jazzy"],
 "a": 2,
 "ex": "容器把 ROS 發行版與 L4T 系統解耦，也讓 Mac 與 Jetson 共用同一 image。A 會毀掉 NVIDIA 的 BSP 支援。B 可行但維護成本高且孤兒化。D 是選項但放棄了生態與 CI 一致性——不是「標準解」。",
 "dig": {"s": "邊緣裝置上 OS 與 ROS 版本解耦", "m": "系統是什麼 Ubuntu 就只能跑對應的 ROS 版本", "t": "L4T 綁定 host OS，但容器內的發行版自由——這是 jetson-containers 專案存在的理由", "p": "解釋 --runtime nvidia 讓容器用到 GPU 的機制（掛什麼進去），與一般 Docker 有何不同"}},
{
 "n": "A5-2", "ty": "debug",
 "q": "容器內 torch.cuda.is_available() 回傳 False，host 上 tegrastats 正常。第一個檢查的是？",
 "o": ["容器啟動是否帶了 --runtime nvidia（或等效設定）",
       "PyTorch 是否需要重新安裝 CPU 版",
       "Jetson 是否過熱觸發了 GPU 保護",
       "CUDA_VISIBLE_DEVICES 是否被設成空值"],
 "a": 0,
 "ex": "沒帶 nvidia runtime，容器內根本沒有 GPU 裝置節點——最常見也最先排除。B 裝錯版本可能，但先查 runtime 成本更低。C 過熱是降頻不是隱藏 GPU。D 可能性存在但罕見於預設環境。",
 "dig": {"s": "容器內 GPU 可見性的分層排查", "m": "host 有 GPU，容器自然就看得到", "t": "容器預設隔離裝置；nvidia runtime 負責把 /dev 節點與函式庫注入——排查從 runtime 到函式庫再到框架", "p": "給我容器內驗證 GPU 的三層檢查指令：裝置節點、CUDA 函式庫、框架 API"}},
{
 "n": "A5-2", "ty": "scenario",
 "q": "「同一個 image 在 Mac 模擬與 Jetson 真機都能跑」的工程價值，最核心的是？",
 "o": ["節省 image 儲存空間",
       "消滅「在我機器上沒問題」",
       "讓 Mac 也能使用 CUDA 加速",
       "避免付兩份 registry 的流量費"],
 "a": 1,
 "ex": "同源 image 讓 CI 驗過的東西就是真機跑的東西，環境漂移歸零。A、D 是次要成本問題。C Mac 上沒有 CUDA，容器也變不出來。",
 "dig": {"s": "environment parity 在機器人開發的意義", "m": "開發環境跟部署環境本來就不可能一樣，測過再部署就好", "t": "arm64 容器讓 Mac 與 Jetson 跑同一 digest 的 image——差異只剩硬體存取，bug 面積大幅縮小", "p": "哪些 bug 仍然只會在真機出現（GPU、裝置、時序）？幫我列出必須上真機驗證的測試清單"}},
{
 "n": "A5-3", "ty": "debug",
 "q": "Mac 與 Jetson 有線直連同網段，topic list 看得到彼此、echo 卻收不到資料。經典成因是？",
 "o": ["兩台機器的 ROS_DOMAIN_ID 不一致",
       "發現用 multicast 通了",
       "Jetson 的 CPU 不足以序列化訊息",
       "兩台機器的 ROS 2 發行版不同"],
 "a": 1,
 "ex": "發現與資料走不同路徑：list 看得到代表發現通，收不到常是 unicast 資料流被防火牆／錯誤的介面綁定擋掉。A domain 不合連 list 都看不到。C CPU 不足是延遲不是全無。D 跨發行版通常仍可通。",
 "dig": {"s": "DDS 發現流量與資料流量的路徑差異", "m": "看得到 topic 就代表網路完全通了", "t": "SPDP 是 multicast、user data 是 unicast——半通狀態（看得見收不到）指向資料路徑被擋", "p": "給我逐步排查腳本：確認 7400 系列埠、防火牆規則、DDS 綁定的網卡各是否正常"}},
{
 "n": "A5-3", "ty": "concept",
 "q": "跨機系統要求 Mac 與 Jetson 時鐘同步（chrony），最直接的受害者是哪類功能？",
 "o": ["帶時間戳的資料融合與 tf 查詢",
       "topic 的發布頻率穩定性",
       "DDS 的節點發現速度",
       "rosbag 的檔案壓縮率"],
 "a": 0,
 "ex": "跨機資料靠時間戳對齊，時鐘漂移直接讓 tf 查詢與融合出現系統性偏差。B 頻率由發布端自己的時鐘決定。C 發現不依賴絕對時間。D 壓縮率與時鐘無關。",
 "dig": {"s": "分散式機器人系統的時鐘一致性", "m": "各機器用自己的時鐘就好，NTP 差個幾百毫秒沒關係", "t": "100ms 的鐘差在 1m/s 移動下是 10cm 的感知錯位；跨機融合要求 ms 級同步（chrony/PTP）", "p": "教我量測兩台機器的實際鐘差（chronyc 或互 ping 時間戳），與判斷是否達標"}},
{
 "n": "A5-3", "ty": "tradeoff",
 "q": "遠端傳輸影像 topic 改用 compressed transport 的代價是？",
 "o": ["兩端增加編解碼 CPU 與些許延遲",
       "影像的解析度會被強制減半",
       "QoS 只能使用 RELIABLE 模式",
       "無法再被 rosbag 錄製"],
 "a": 0,
 "ex": "壓縮用 CPU 換頻寬，訂閱端要能解壓——這是明確可估的代價。B 解析度不變（品質參數另計）。C QoS 不受影響。D 照樣能錄，錄的是壓縮流。",
 "dig": {"s": "頻寬 vs CPU 的傳輸取捨", "m": "壓縮永遠是免費的頻寬節省", "t": "Jetson 的 CPU 也是稀缺資源；量化兩端成本後再決定壓縮等級，必要時用硬體編碼器", "p": "Jetson 上用硬體 JPEG/H.264 編碼影像 topic 的方案有哪些？各自的 ROS 2 整合度如何？"}},
]
