# -*- coding: utf-8 -*-
"""題庫（自動修復後重生成）"""

QA = [
{
 "n": "A0-1", "ty": "concept",
 "q": "在 Apple Silicon Mac 上跑 ROS 2，官方支援度最好的做法是？",
 "o": ["UTM 開 x86_64 Ubuntu 虛擬機再裝 ROS 2",
       "brew 直接在 macOS 安裝 ROS 2 套件",
       "Rosetta 2 轉譯 x86_64 的 ROS 2 程式",
       "Docker 跑 linux/arm64 的 Ubuntu 容器"],
 "a": 3,
 "ex": "Ubuntu arm64 是 Tier-1 平台，容器內等同原生。B 錯在 macOS 是 Tier-3，只能自己編譯且 best-effort。C 混淆了 CPU 轉譯與作業系統支援，效能與相容都差。A 是模擬 x86，比原生 arm64 慢一個數量級。",
 "dig": {"s": "ROS 2 的平台支援分級（Tier 1/2/3）與 Apple Silicon 的正確跑法", "m": "只要是 Mac 就得用虛擬機或 Rosetta 模擬 x86 才能跑 ROS 2", "t": "Ubuntu arm64 是 Tier-1，M 系列 Mac 用 Docker 跑 arm64 容器就是原生速度", "p": "給我一份最小的 compose.yaml，能在 Mac 上跑 ROS 2 Jazzy 並掛載本機 workspace"}},
{
 "n": "A0-1", "ty": "debug",
 "q": "兩個 ROS 2 容器各自用預設 bridge 網路啟動，互相看不到對方的 topic。最可能的原因是？",
 "o": ["容器的 ROS_VERSION 環境變數沒對齊",
       "topic 名稱在容器內會自動加上主機名前綴",
       "兩個容器安裝了不同版本的 rclpy，API 彼此不相容",
       "DDS 依賴的 multicast 在 bridge 網路下不通"],
 "a": 3,
 "ex": "DDS 發現靠 multicast announce，Docker bridge 預設擋掉它。A 與 C 只影響 API 相容，不影響發現。B 描述的行為不存在——命名空間要自己設。",
 "dig": {"s": "DDS 發現機制對網路環境（multicast）的依賴", "m": "容器只要能 ping 通，ROS 2 節點就能互相發現", "t": "發現靠 multicast/週期性 announce，bridge NAT 會擋；要用 host network、同一 network 或 discovery server", "p": "給我一個可以直接跑的實驗：兩個容器在 bridge 與 host network 下各測一次 talker/listener，並解釋結果"}},
{
 "n": "A0-1", "ty": "tradeoff",
 "q": "Mac 開發 ROS 2 GUI（RViz 等），實務上比較穩的選擇是？",
 "o": ["XQuartz 做 X11 轉發，最貼近原生體驗",
       "把 Mac 換成雙系統直接開 Ubuntu",
       "GUI 全部放棄，只用 CLI 完成所有觀測",
       "容器內跑 VNC 或改用 Foxglove 這類 Web 工具"],
 "a": 3,
 "ex": "VNC/Web 工具不依賴脆弱的 X11 管線，跨平台穩定。A 的 XQuartz 常有 OpenGL 與延遲問題。B 代價過大且 Apple Silicon 裝 Ubuntu 桌面另有一堆坑。C 會在視覺化除錯（tf、影像）時寸步難行。",
 "dig": {"s": "跨平台 ROS 2 視覺化的工程取捨", "m": "X11 轉發是 Linux GUI 跨機顯示的標準解，理應最穩", "t": "X11 轉發對 3D 加速與版本極敏感；VNC 或 Foxglove（WebSocket）才是低摩擦解", "p": "給我在 ROS 2 容器裡啟動 foxglove_bridge 並從 Mac 瀏覽器連上的完整步驟"}},
{
 "n": "A0-2", "ty": "debug",
 "q": "colcon build 成功後執行 `ros2 run my_pkg my_node` 卻報 package not found，最常見的原因是？",
 "o": ["package.xml 裡缺少 exec_depend 宣告",
       "colcon 沒有加 --symlink-install 參數",
       "沒有重新 source install/setup.bash",
       "節點檔案忘了加可執行權限 chmod +x"],
 "a": 2,
 "ex": "build 產物要靠 source overlay 才會進 AMENT_PREFIX_PATH，新開的 shell 或忘了 source 就找不到。A 影響依賴解析而非自家 package 尋找。B 只影響改檔後要不要重 build。D 對 ament_python 的 entry point 不適用。",
 "dig": {"s": "ament workspace 的 underlay/overlay 與 source 機制", "m": "build 完成後 package 就註冊到系統裡，任何 shell 都找得到", "t": "colcon 只把產物放進 install/，是 source setup.bash 改了環境變數才讓 ros2 找得到", "p": "給我一組指令，印出 source 前後 AMENT_PREFIX_PATH 的差異並解釋每一段路徑的作用"}},
{
 "n": "A0-2", "ty": "concept",
 "q": "`colcon build --symlink-install` 的效果是？",
 "o": ["把依賴以連結方式共享，縮小 install 體積",
       "跳過已建過的 package，加速整體 build",
       "允許多個 workspace 共用同一份 build 目錄",
       "Python 原始檔以 symlink 進 install"],
 "a": 3,
 "ex": "symlink 讓 install 指回 src 的原始檔，直譯語言改完即生效。A 描述的機制不存在。B 是增量編譯本來就有的行為。C 混淆了 overlay 機制與 build 目錄。",
 "dig": {"s": "colcon 的 symlink-install 對開發迭代速度的意義", "m": "改任何檔案都要重跑 colcon build 才會生效", "t": "symlink-install 讓 Python/launch/config 改動即時生效，只有 C++ 與新增檔案需要重 build", "p": "列出哪些改動仍然必須重跑 colcon build 的完整清單，並解釋原因"}},
{
 "n": "A0-2", "ty": "tradeoff",
 "q": "自訂 msg 通常放獨立的 interface package 而不是跟節點放一起，主因是？",
 "o": ["ros2 interface show 只能搜到獨立包裡的型別",
       "msg 生成需要 CMake，跟 ament_python 不能混用",
       "獨立 package 能讓 msg 的序列化速度更快",
       "避免下游為了型別被迫依賴整包實作與其依賴"],
 "a": 3,
 "ex": "介面是契約，分離後下游只依賴輕量契約包。B 只說對一半——確實要 ament_cmake，但這是做法問題不是不可混用的主因。C 序列化與包結構無關。A 的限制不存在。",
 "dig": {"s": "interface package 分離的依賴設計理由", "m": "msg 放哪裡只是目錄整潔問題，不影響架構", "t": "介面獨立成包是為了讓依賴圖乾淨：下游依賴契約而非實作", "p": "給我一個雙 package 範例結構（interfaces + node），並示範第三個 package 只依賴 interfaces 的寫法"}},
{
 "n": "A0-3", "ty": "debug",
 "q": "`ros2 topic list` 看得到 /scan，但 `ros2 topic echo /scan` 一直沒輸出。下一步最有效的診斷是？",
 "o": ["重啟 daemon：ros2 daemon stop 再 start",
       "加大 echo 的 buffer 參數再等 30 秒",
       "ros2 node list 確認發布節點還活著",
       "ros2 topic info /scan -v 檢查 QoS 與端點"],
 "a": 3,
 "ex": "info -v 一次看到 pub/sub 數量與雙方 QoS，是收不到時的第一刀。A 只解「列表都看不到」的快取問題。C 資訊量少，且 topic 有端點時節點多半活著。B 是等運氣不是診斷。",
 "dig": {"s": "topic 可見但收不到資料時的 CLI 診斷順序", "m": "topic 列得出來就代表通訊正常，收不到是程式 bug", "t": "列表只代表有端點註冊；能不能收到取決於 QoS 相容與發布行為，info -v 才看得到", "p": "整理一張「topic 收不到」的診斷決策樹，每個分支配一條 CLI 指令"}},
{
 "n": "A0-3", "ty": "concept",
 "q": "`ros2 topic hz` 顯示的頻率明顯低於發布端設定值，且 window 內抖動很大。不能從這個輸出直接下的結論是？",
 "o": ["訂閱路徑上存在某種瓶頸或丟包",
       "接收端量到的到達間隔不穩定",
       "平均到達頻率低於名目設定值",
       "發布端的程式碼一定寫錯了頻率"],
 "a": 3,
 "ex": "hz 量的是接收端到達率，瓶頸可能在網路、QoS、序列化或 CPU，未必是發布端。A、B、C 都是輸出可直接支持的敘述。",
 "dig": {"s": "ros2 topic hz 的量測位置與可推論範圍", "m": "hz 顯示多少，發布端就是發了多少", "t": "hz 是接收端視角：發布率、傳輸、QoS、接收端負載全部疊加後的結果", "p": "設計一個實驗分離「發布端慢」與「傳輸丟」兩種成因，各用什麼指令與 QoS 設定驗證"}},
{
 "n": "A0-3", "ty": "scenario",
 "q": "你接手一台陌生機器人，只有 SSH。要最快建立系統全貌，第一組指令選？",
 "o": ["grep 整個 launch 目錄還原啟動結構",
       "ros2 bag record -a 錄十分鐘慢慢分析",
       "ros2 doctor --report 讀完整份報告",
       "ros2 node list 加上對每個節點 node info"],
 "a": 3,
 "ex": "node list + node info 直接產出「誰在跑、誰跟誰講話」的活拓撲。B 拿到資料但沒結構，還吃磁碟。C 偏環境健檢，不給拓撲。A 看的是應然不是實然——跑起來的系統可能跟 launch 檔不同。",
 "dig": {"s": "快速盤點陌生 ROS 2 系統的方法", "m": "先讀 launch 檔就能了解系統結構", "t": "launch 是應然、執行中拓撲是實然；用 node/topic CLI 先量實然再對照應然", "p": "寫一個 shell 腳本，自動產出目前系統的節點-topic 邊清單（誰發誰收）"}},
{
 "n": "A0-4", "ty": "concept",
 "q": "turtlesim 裡「產生第二隻烏龜」用的是 service 而不是 topic，因為這個操作？",
 "o": ["需要傳輸的資料量比座標訊息更大",
       "頻率太低，topic 會浪費頻寬",
       "必須廣播給所有節點同時知道",
       "是一次性請求且呼叫方需要成功與否的回覆"],
 "a": 3,
 "ex": "請求/回應語意（做一次、告訴我結果）正是 service 的定義。A 資料量與原語選擇無關。C 廣播反而是 topic 的特性。B 低頻 topic 幾乎不耗資源，頻寬不是理由。",
 "dig": {"s": "topic 與 service 的語意分工", "m": "低頻操作用 service、高頻用 topic，是頻率決定的", "t": "決定因素是語意：連續資料流用 topic，一次性請求且要回覆用 service", "p": "給我五個機器人操作情境，讓我逐一判斷該用 topic/service/action，再公布你的答案與理由"}},
{
 "n": "A0-4", "ty": "debug",
 "q": "rosbag 重播 turtlesim 的 /turtle1/cmd_vel，烏龜卻不動。最可能的解釋是？",
 "o": ["錄製時沒有加 --include-hidden-topics",
       "turtlesim 拒絕來自非鍵盤節點的指令",
       "bag 檔必須先轉成 MCAP 格式才能重播",
       "重播的 topic 名稱或型別與訂閱端不匹配"],
 "a": 3,
 "ex": "重播是普通 publisher，名稱/型別對不上就沒人收——用 topic info 對照即可驗證。A 的參數與 cmd_vel 無關。C 兩種格式都可直接播。B 的來源檢查機制不存在，DDS 不認發送者身分。",
 "dig": {"s": "rosbag 重播的本質（就是再發布一次）", "m": "bag 重播有特殊通道，跟一般 topic 通訊不同", "t": "重播就是一個普通 publisher，所有 topic 規則（名稱、型別、QoS）照常適用", "p": "示範用 ros2 bag play --remap 把錄好的 topic 重導到另一個名稱"}},
{
 "n": "A0-4", "ty": "scenario",
 "q": "你想確認自己真的掌握了 CLI 基礎。以下哪個測驗最能證明？",
 "o": ["把官方教學每一頁重做一遍不出錯",
       "背出 ros2 topic 所有子指令與參數",
       "限時不看文件，用 CLI 完成生龜、控龜、錄放",
       "向別人口頭解釋每個指令的用途"],
 "a": 2,
 "ex": "限時、無文件、有具體產出——可判定且測的是提取能力。A 是跟著做，測不出獨立能力。B 背誦不等於會用。D 口頭解釋無法驗證操作熟練度。",
 "dig": {"s": "怎麼驗證自己真的會一項操作技能", "m": "教學做完一遍沒卡住，就代表學會了", "t": "跟做測的是閱讀理解；能力要用「無提示提取」驗證——限時完成一個沒有腳本的任務", "p": "幫我再出三個 turtlesim 情境挑戰，難度遞增，每個限時 5 分鐘"}},
{
 "n": "A1-1", "ty": "concept",
 "q": "改了自訂 msg 的欄位名稱後重新 build，舊版訂閱端和新版發布端一起跑會發生什麼？",
 "o": ["訂閱端 crash 並印出型別轉換例外",
       "欄位自動對齊，缺的欄位補預設值",
       "連線建立但收到的資料位移錯亂",
       "型別 hash 不匹配，雙方不建立連線"],
 "a": 3,
 "ex": "ROS 2 用型別描述比對，不一致就不配對——安靜地各說各話。B 是 protobuf 這類向後相容格式的行為。C 是 C 結構體硬轉的想像。A 不會發生，因為連線根本不建立。",
 "dig": {"s": "msg 介面演進時的相容性行為", "m": "訊息格式改了，舊訂閱端會收到錯位的資料或直接報錯", "t": "型別不一致時 DDS 端點不匹配，症狀是「安靜地收不到」而非報錯", "p": "介面要加欄位時，實務上的演進策略有哪些（新 topic、版本後綴、兼容欄位）？各給例子"}},
{
 "n": "A1-1", "ty": "debug",
 "q": "同一個感測器節點要跑兩份（左右各一），最乾淨的做法是？",
 "o": ["複製整個 package 改名為 left/right 兩份",
       "在程式碼裡讀環境變數決定 topic 名稱",
       "launch 時用 namespace 或 remap 隔離兩個實例",
       "兩份共用 topic，訊息裡加欄位區分左右"],
 "a": 2,
 "ex": "namespace/remap 是 ROS 2 內建的多實例機制，程式碼零修改。A 造成雙倍維護。B 重造了 remap 已有的輪子。D 把路由邏輯推給所有下游，每個訂閱者都得過濾。",
 "dig": {"s": "ROS 2 的名稱重映射與命名空間機制", "m": "要跑兩份節點就得在程式碼裡做出區分", "t": "名稱解析是 launch 層的事：node 內用相對名稱，實例化時用 namespace/remap 隔離", "p": "給我一個 launch 檔範例：同一個節點起兩份，各自的 topic 與參數完全隔離"}},
{
 "n": "A1-1", "ty": "tradeoff",
 "q": "一個 30Hz 的影像 topic 和一個「機器人模式切換」事件，都用 topic 傳。模式切換訊息設計上要特別考慮什麼？",
 "o": ["提高發布頻率到 30Hz 以確保對方收到",
       "改用更大的 history depth 硬撐可靠性",
       "壓縮訊息體積讓它跟影像走同一條通道",
       "晚加入的訂閱者要能拿到最後狀態（durability）"],
 "a": 3,
 "ex": "狀態型訊息的重點是 late-joiner 能取得現值，TRANSIENT_LOCAL 正是為此存在。A 用重送模擬狀態是浪費又不可靠。B 深度解決不了「訂閱前就發過了」。C 體積與這個問題無關。",
 "dig": {"s": "事件流 vs 狀態流的 topic 設計差異", "m": "topic 就是 topic，訊息類型不影響設計", "t": "狀態型 topic 要用 durability 讓晚到者拿到現值；事件型要考慮丟了怎麼辦——兩種設計完全不同", "p": "用 Kafka 的 compacted topic 類比 TRANSIENT_LOCAL，指出這個類比哪裡準、哪裡會誤導"}},
{
 "n": "A1-2", "ty": "concept",
 "q": "「移動手臂到目標位姿、過程要能取消、要回報進度」——選哪個通訊原語？",
 "o": ["service：請求後等待完成回覆",
       "參數：把目標寫進參數由節點輪詢",
       "topic：發一個指令 topic、再收一個狀態回報 topic",
       "action：goal / feedback / cancel 齊備"],
 "a": 3,
 "ex": "長任務＋進度＋取消是 action 的定義場景。A 缺 feedback 與 cancel，還會卡住呼叫端。C 能拼出來但要自己造 goal 管理與取消協定。B 濫用了配置機制。",
 "dig": {"s": "action 的適用場景與其相對 service 的增量", "m": "service 加個進度 topic 就等於 action，不必多學一個原語", "t": "action 內建 goal 狀態機、feedback、cancel 與多 goal 管理——自己拼會漏掉取消與競態", "p": "列出 action 的完整狀態機（goal states），並解釋 cancel 請求後 server 可以有哪些合法反應"}},
{
 "n": "A1-2", "ty": "debug",
 "q": "在 rclpy 的 subscriber callback 裡同步呼叫 `client.call()`，程式卡死。根本原因是？",
 "o": ["rclpy 的 service client 只支援 async 語法",
       "service server 沒開多執行緒模式",
       "DDS 不允許在 callback 中發起新請求",
       "同一個 executor 執行緒在等自己有空處理回覆"],
 "a": 3,
 "ex": "單執行緒 executor 正在跑這個 callback，而回覆的處理也排在同一條佇列——自己等自己，永遠等不到。B 是 server 端的事，卡死在 client 端。C 沒有這種限制。A call() 確實存在，只是在這個情境會死鎖。",
 "dig": {"s": "executor 單執行緒模型下的自我死鎖", "m": "卡住是因為 server 太慢或網路問題", "t": "回覆已經到了，但處理它的執行緒正被你的 callback 佔住——這是排程死鎖不是通訊問題", "p": "給我一段可直接跑的最小 repro，再給兩種修法（async await 與 Reentrant group）的完整程式"}},
{
 "n": "A1-2", "ty": "scenario",
 "q": "設計「韌體更新」API。更新耗時 3 分鐘、可能失敗、失敗要能中止。哪個設計最合理？",
 "o": ["service 觸發，client 設 200 秒 timeout 等待",
       "topic 發「開始更新」，另一 topic 收結果",
       "action：goal 帶版本、feedback 回進度、可 cancel",
       "service 觸發後，client 輪詢一個狀態 service"],
 "a": 2,
 "ex": "長任務、進度、可中止——三個需求 action 全部原生支援。A 佔著連線乾等且無法中止。B 沒有關聯 ID，兩次更新會混淆。D 是自製的 poor man's action，還要自己定義取消協定。",
 "dig": {"s": "把業務需求翻譯成正確的 ROS 2 通訊原語", "m": "service + timeout 就能處理所有一次性操作", "t": "timeout 只是放棄等待，任務仍在跑；需要中止語意就必須用 action 的 cancel", "p": "幫我設計這個韌體更新 action 的 .action 檔內容（goal/result/feedback 欄位），並討論失敗碼設計"}},
{
 "n": "A1-3", "ty": "concept",
 "q": "ROS 2 參數與 topic 最本質的差別是？",
 "o": ["參數屬於單一節點，由該節點宣告與持有",
       "參數會自動存檔，重啟後保留上次的值",
       "參數只能是數字與字串，topic 可以是任意型別",
       "參數的更新速度比 topic 慢一個數量級"],
 "a": 0,
 "ex": "參數是節點的配置介面，作用域就是那個節點；topic 是節點間的資料流。B 相反——參數預設不持久化，重啟回到宣告值。C 參數也支援 bool/陣列等。D 效能不是本質差異。",
 "dig": {"s": "參數的作用域與生命週期", "m": "參數像一個全域的 key-value store，大家都能讀寫", "t": "每個參數屬於特定節點；跨節點「共用」其實是各自宣告、由 YAML 統一注入", "p": "示範 ros2 param dump 匯出一個節點的參數再在下次啟動載回去的完整流程"}},
{
 "n": "A1-3", "ty": "debug",
 "q": "YAML 參數檔載入後，節點行為沒變。除了檔案路徑錯誤，最常見的原因是？",
 "o": ["YAML 用了兩格縮排而非四格",
       "launch 檔沒有開啟 allow_undeclared 旗標",
       "參數檔必須是 JSON，YAML 已棄用",
       "節點名稱或參數層級與檔內宣告對不上"],
 "a": 3,
 "ex": "YAML 以節點名為 key（含 namespace），對不上就整段被跳過且不報錯。A 縮排格數不影響合法 YAML。C 完全相反。B 該旗標影響的是未宣告參數能不能設，不是常見主因。",
 "dig": {"s": "參數 YAML 的結構與節點名匹配規則", "m": "參數檔載入失敗會報錯，沒報錯就是有載入", "t": "節點名對不上時是安靜跳過；驗證要用 ros2 param get 實際讀回來", "p": "給一個含 namespace 的節點的正確參數 YAML 範例，並展示三種常見寫錯法與各自症狀"}},
{
 "n": "A1-3", "ty": "scenario",
 "q": "同一套系統要能一鍵切「模擬模式」與「真機模式」，launch 設計上最合理的是？",
 "o": ["維護 sim.launch 與 real.launch 兩個檔案",
       "用環境變數在每個節點裡各自判斷模式",
       "真機模式另外用 shell script 啟動",
       "一個 launch 檔收 mode argument"],
 "a": 3,
 "ex": "launch argument + 條件（IfCondition）讓共通部分只寫一次，差異點集中管理。A 會讓兩檔逐漸漂移。B 把編排邏輯散進每個節點。C 繞過 launch 的依賴與參數管理。",
 "dig": {"s": "launch 的參數化與條件啟動", "m": "不同配置就該用不同的 launch 檔，比較清楚", "t": "配置差異用 argument 表達、共通結構只寫一份——跟 IaC 的 DRY 原則同構", "p": "寫一個帶 mode:=sim|real 的 launch 檔骨架，sim 模式多起一個模擬器節點"}},
{
 "n": "A1-4", "ty": "concept",
 "q": "SingleThreadedExecutor 下，一個 callback 執行 10 秒會造成？",
 "o": ["其他 callback 改由備援執行緒接手",
       "executor 偵測逾時後強制中斷該 callback",
       "只有同一個 topic 的後續訊息被延遲",
       "該節點所有其他 callback 排隊 10 秒"],
 "a": 3,
 "ex": "單執行緒 executor 一次只跑一個 callback，timer、subscriber、service 全部共用那條執行緒。A 沒有備援執行緒這種東西。C 影響範圍是整個 executor 不是單一 topic。B executor 不會搶佔或中斷 callback。",
 "dig": {"s": "executor 的單執行緒排程模型", "m": "每個 subscriber 有自己的執行緒，慢 callback 只拖累自己", "t": "預設所有 callback 共用一條執行緒；一個 hang 全部停——這是『節點活著但不動』的主因", "p": "給我一段 demo：timer 每秒印 tick，另一個 callback sleep 10 秒，觀察 tick 停頓；再改成 MultiThreadedExecutor 對照"}},
{
 "n": "A1-4", "ty": "tradeoff",
 "q": "把節點全面改成 MultiThreadedExecutor + Reentrant group 的主要代價是？",
 "o": ["callback 可並行與重入，共享狀態要自己上鎖",
       "記憶體用量大約增加一個數量級",
       "無法再使用 service 與 action 介面",
       "訊息傳遞延遲顯著上升"],
 "a": 0,
 "ex": "Reentrant 表示同一 callback 也可能同時跑兩份，所有共享狀態進入多執行緒世界。B 多幾條執行緒的記憶體成本很小。C 介面照常可用。D 延遲通常持平或下降。",
 "dig": {"s": "callback group 的並行語意與資料競態風險", "m": "開多執行緒 executor 就是免費的效能升級", "t": "並行是把鎖的責任轉到你手上；MutuallyExclusive group 是預設保護，改 Reentrant 前要先盤點共享狀態", "p": "設計一個因 Reentrant 而出現 race 的最小案例，再用 MutuallyExclusive group 修好它"}},
{
 "n": "A1-4", "ty": "debug",
 "q": "節點的 timer 應該 10Hz 觸發，實測只有 3Hz 且不穩。除了系統過載，最該懷疑的是？",
 "o": ["timer 精度上限就是 3Hz 左右",
       "DDS 把 timer 事件當低優先級處理",
       "某些 callback 執行過久",
       "節點沒有宣告 use_sim_time 參數"],
 "a": 2,
 "ex": "timer 與其他 callback 共搶 executor，長 callback 會讓 timer 錯過觸發點。A timer 精度遠高於此。B timer 是 executor 內部事件，與 DDS 無關。D 只在模擬時鐘情境有影響。",
 "dig": {"s": "timer 抖動與 executor 佔用的關係", "m": "timer 設多少就會跑多少，不準是系統時鐘問題", "t": "timer 觸發要等 executor 有空；診斷第一步是找出佔住執行緒的長 callback", "p": "寫一個量測工具節點：記錄自己每個 callback 的執行時間分佈，找出壓垮 timer 的兇手"}},
{
 "n": "A1-5", "ty": "debug",
 "q": "publisher 設 BEST_EFFORT、subscriber 要求 RELIABLE。結果是？",
 "o": ["以較嚴格的 RELIABLE 為準建立連線",
       "subscriber 啟動時直接拋出 QoS 例外",
       "連上但只在網路好的時候收得到",
       "不建立連線，且預設不會有任何錯誤輸出"],
 "a": 3,
 "ex": "請求端要求的保證高於提供端能給的，配對失敗且安靜。A 相容性協商只會向下，不會把 BEST_EFFORT 升級。C 描述的是連上後的 BEST_EFFORT 行為，但這裡根本沒連上。B 預設不拋錯，要自己註冊 event callback 才看得到。",
 "dig": {"s": "QoS 相容性規則（request vs offered）", "m": "QoS 不合會自動取交集，頂多品質差一點", "t": "offered 必須不低於 requested 才配對；不合就是安靜的零連線", "p": "給我 QoS 相容矩陣（reliability × durability），並附一段註冊 incompatible QoS event 的程式碼"}},
{
 "n": "A1-5", "ty": "tradeoff",
 "q": "30Hz 相機影像 topic，網路偶爾壅塞。QoS 選 BEST_EFFORT 而非 RELIABLE 的理由是？",
 "o": ["BEST_EFFORT 會自動壓縮影像節省頻寬",
       "RELIABLE 不支援 sensor_msgs 這類大訊息",
       "丟舊幀比重傳舊幀好——重傳會讓延遲雪崩",
       "BEST_EFFORT 的 CPU 使用量高但延遲穩定"],
 "a": 2,
 "ex": "影像的價值在新鮮度，壅塞時 RELIABLE 的重傳佇列會讓延遲持續累積。A 沒有自動壓縮這回事。B RELIABLE 傳大訊息完全可行。D 說反了，BEST_EFFORT 的 CPU 開銷較低。",
 "dig": {"s": "資料時效性 vs 完整性的 QoS 取捨", "m": "RELIABLE 比較可靠，所以永遠是比較安全的選擇", "t": "對時效性資料，重傳舊資料是負價值；sensor data profile 用 BEST_EFFORT 是深思熟慮的預設", "p": "什麼樣的 topic 反而必須 RELIABLE？給三個例子並解釋丟一筆的後果"}},
{
 "n": "A1-5", "ty": "scenario",
 "q": "地圖 topic 只在啟動時發一次。RViz 晚了 30 秒才啟動也要看得到地圖，靠哪個 QoS 設定？",
 "o": ["history depth 設成 1000 以上",
       "deadline 設成 30 秒以上",
       "liveliness 改成 MANUAL_BY_TOPIC",
       "durability 設 TRANSIENT_LOCAL"],
 "a": 3,
 "ex": "TRANSIENT_LOCAL 讓 publisher 為晚到的訂閱者保留最後樣本——latched topic 的機制。A depth 只影響已連線後的緩衝。B deadline 是頻率契約，跟補發無關。C liveliness 是存活宣告機制。",
 "dig": {"s": "durability 的 late-joiner 語意", "m": "只要 buffer 開夠大，晚加入的訂閱者就能收到歷史訊息", "t": "history 是連線後的佇列；連線前的樣本要靠 TRANSIENT_LOCAL 補發，且 sub 也要同設定", "p": "示範 map topic 的正確 QoS 寫法（pub 與 sub 兩側），並解釋為何只設一側會失敗"}},
{
 "n": "A1-6", "ty": "concept",
 "q": "ROS 2 不需要 roscore/master，因為 DDS 的發現機制是？",
 "o": ["各 participant 週期性 multicast 宣告自己",
       "第一個啟動的節點自動兼任註冊中心",
       "所有節點透過共享記憶體交換端點清單",
       "由 rmw 抽象層在背景維護一個隱藏的中央端點資料庫"],
 "a": 0,
 "ex": "SPDP/SEDP 讓每個 participant 自我宣告、彼此配對，沒有單點。B 沒有這種選主機制。C 共享記憶體只用於同機資料傳輸的最佳化。D rmw 是抽象層不是註冊中心。",
 "dig": {"s": "DDS 的去中心化發現（SPDP/SEDP）", "m": "一定有個隱藏的中央服務在管節點註冊，只是 ROS 2 藏起來了", "t": "發現是純 peer-to-peer 的 multicast 宣告與配對，這也是它在受限網路下容易壞的原因", "p": "用 tcpdump 抓 port 7400 的 SPDP 封包，帶我讀懂一個 participant announcement 的內容"}},
{
 "n": "A1-6", "ty": "debug",
 "q": "公司 Wi-Fi 下，Mac 與 Jetson 同 domain id 卻互相看不見。最可能的網路層原因是？",
 "o": ["Wi-Fi 鏈路的 MTU 太小，裝不下完整的 DDS 發現封包",
       "DDS 在無線網路下會自動停用發現",
       "兩台機器的 hostname 有重複",
       "AP 啟用了 client isolation 或擋 multicast"],
 "a": 3,
 "ex": "企業 AP 常見 client isolation／multicast 過濾，發現封包出不去。A MTU 問題會影響大訊息不是發現。C hostname 與 DDS 發現無關（用 GUID）。B 沒有這種自動停用。",
 "dig": {"s": "受限網路環境下的 DDS 發現失敗模式", "m": "兩台機器互相 ping 得到，ROS 2 就應該通", "t": "unicast 通不代表 multicast 通；解法是 initial peers 清單或 discovery server", "p": "給我 CycloneDDS 設定 unicast initial peers 的 XML 範例，以及驗證是否生效的方法"}},
{
 "n": "A1-6", "ty": "tradeoff",
 "q": "大型部署改用 Fast DDS Discovery Server 取代 multicast 發現，主要的代價是？",
 "o": ["訊息資料流也必須繞經 server 轉發",
       "只能在同一台機器上執行所有節點",
       "引入一個要維運的服務與單點考量",
       "與 rosbag、Foxglove 等工具不相容"],
 "a": 2,
 "ex": "discovery server 是要部署、監控、考慮冗餘的元件——典型的中心化代價。A 資料流仍是 peer-to-peer，server 只管發現。B 恰恰相反，它就是為跨網段設計。D 工具照常運作。",
 "dig": {"s": "中心化發現與去中心化發現的取捨", "m": "加了 discovery server 之後所有流量都會經過它，會成為頻寬瓶頸", "t": "server 只交換端點資訊，資料仍點對點；代價是維運與可用性設計，不是頻寬", "p": "設計一個含備援的 discovery server 部署方案（兩台 server），並說明 client 端設定"}},
{
 "n": "A1-7", "ty": "concept",
 "q": "tf2 查詢 lookup_transform 時常指定過去的時間戳而非「現在」，因為？",
 "o": ["tf2 的 API 不接受目前時間作為參數",
       "現在時刻的變換要等下一幀才會發布",
       "過去的變換數值比較平滑，雜訊較小",
       "感測資料帶著它被擷取當下的時間"],
 "a": 3,
 "ex": "座標變換是時間的函數：50ms 前拍的點雲要用 50ms 前的機器人位姿來轉。A 接受，只是常常不該用。C 平滑與否不是動機。B 描述的現象存在但只是結果，不是設計理由。",
 "dig": {"s": "tf2 的時間對齊語意", "m": "查變換就是查「兩個座標系現在差多少」", "t": "正確問法是「資料誕生那一刻差多少」——tf buffer 就是為了回答過去式的查詢", "p": "給一個具體數字例子：機器人以 1m/s 移動，用錯 100ms 的時間戳會造成多大的點雲偏移"}},
{
 "n": "A1-7", "ty": "debug",
 "q": "log 出現 TF_OLD_DATA 警告刷屏。最典型的成因是？",
 "o": ["某個來源在重複發布過舊時間戳的變換（常見於 bag 重播沒重設）",
       "tf 樹裡有兩個節點爭相發布同一段變換",
       "static transform 的發布頻率設定過低",
       "buffer 的容量參數小於系統需求"],
 "a": 0,
 "ex": "TF_OLD_DATA 指收到比 buffer 已有資料更舊的變換，經典場景是 bag 循環重播而沒 reset 時間。B 會產生 jump 或衝突警告，訊息不同。C static transform 不需要頻率。D buffer 太小造成的是查不到，不是舊資料警告。",
 "dig": {"s": "tf2 錯誤訊息的分類診斷", "m": "tf 警告都是同一類問題，重啟就好", "t": "TF_OLD_DATA／extrapolation／frame not exist 三類各有明確成因，訊息本身就指出方向", "p": "整理 tf2 三大類錯誤訊息的判讀表：訊息長相 → 成因 → 第一個檢查動作"}},
{
 "n": "A1-7", "ty": "scenario",
 "q": "重播 bag 給感知節點除錯，節點一直丟「查無變換」。第一個要檢查的是？",
 "o": ["bag 裡是否漏錄了 /tf_static",
       "感知節點訂閱的 QoS 是否被設成 BEST_EFFORT 而丟包",
       "節點是否開了 use_sim_time 且 bag play 有發 /clock",
       "重播速度是否需要降到 0.5 倍"],
 "a": 2,
 "ex": "重播世界的時間是 bag 時間，節點不用 sim time 就會拿牆鐘查 bag 時代的變換——永遠查不到。A 也可能，但第一檢查點是時鐘，因為它影響所有查詢。B QoS 影響收不收得到，不是查詢時間。D 速度不解決時間基準錯誤。",
 "dig": {"s": "use_sim_time 與 bag 重播的時鐘一致性", "m": "bag 播出來的資料跟即時資料沒有差別", "t": "bag 資料帶著錄製時代的時間戳；整個系統要切到 /clock 驅動的模擬時間才對得上", "p": "給我 ros2 bag play 配 --clock 與節點設 use_sim_time 的完整除錯流程"}},
]
