apiVersion: v1
kind: ConfigMap
metadata:
  name: openlineage-config
data:
  OPENLINEAGE_NAMESPACE: "{{ .Values.openlineage.namespace }}"
  OPENLINEAGE_URL: "{{ .Values.openlineage.transport.url }}"
  OPENLINEAGE_TRANSPORT: "{{ .Values.openlineage.transport.type }}"
