apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-defaults
  namespace: {{ .Values.global.namespace }}
data:
  spark-defaults.conf: |
    spark.jars.packages io.openlineage:openlineage-spark_2.13:1.45.0
    spark.extraListeners io.openlineage.spark.agent.OpenLineageSparkListener
    spark.openlineage.transport.type {{ .Values.openlineage.transport.type }}
    spark.openlineage.transport.url {{ .Values.openlineage.transport.url }}
    spark.openlineage.namespace {{ .Values.openlineage.namespace }}
    spark.openlineage.facets.custom_environment=local-minimal
